return{
    'Eandrju/cellular-automaton.nvim',
    'junegunn/goyo.vim',
    'terrortylor/nvim-comment',
    'neovim/nvim-lspconfig',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-path',
    'hrsh7th/cmp-cmdline',
    'hrsh7th/nvim-cmp',
    'tpope/vim-surround',
    'jiangmiao/auto-pairs',
    'vim-airline/vim-airline',
    'nvim-tree/nvim-tree.lua',
    'dylanaraps/wal.vim',
    'vimwiki/vimwiki',
    { 'ShaiberAlon/snakemake-vim', rtp = 'misc/vim/'},
    {"nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
    -- Color Schemes
    'rose-pine/neovim',
    'sainnhe/everforest',
    'folke/tokyonight.nvim',
    'ray-x/aurora',
    'scottmckendry/cyberdream.nvim',
    'rebelot/kanagawa.nvim',
    'neanias/everforest-nvim',
    -- Local Plugins
    { dir = '~/.config/nvim/plugins/f9', dev = true },
    { dir = '~/.config/nvim/plugins/setcolors', dev = true },
}
