return{
    'neovim/nvim-lspconfig',
    'hrsh7th/cmp-nvim-lsp',
    'hrsh7th/cmp-buffer',
    'hrsh7th/cmp-path',
    'hrsh7th/cmp-cmdline',
    'hrsh7th/nvim-cmp',
    'tpope/vim-surround',
    'jiangmiao/auto-pairs',
    'vim-airline/vim-airline',
    'nvim-tree/nvim-tree.lua',
    'ShaiberAlon/snakemake-vim',
    'dylanaraps/wal.vim',
    {"nvim-treesitter/nvim-treesitter", build = ":TSUpdate"},
    -- Color Schemes
    'rose-pine/neovim',
    'sainnhe/everforest',
    'folke/tokyonight.nvim',
    'ray-x/aurora',
    'scottmckendry/cyberdream.nvim',
    'rebelot/kanagawa.nvim',
    'neanias/everforest-nvim',
    { dir = '~/.config/nvim/plugins/f9', dev = true },
    { dir = '~/.config/nvim/plugins/setcolors', dev = true },
}
