# If not running interactively, don't do anything
[[ $- != *i* ]] && return

cl () { cd "$1" && ls --color=auto ;}
lt () { [[ -z $1 ]] && ls -lcth | head || ls -lth $1 | head ;}
mkcd () { mkdir -p "$1" && cd "$1" }
.. () { [[ $1 =~ ^[2-9]$ ]] && for i in $(seq $1); do cd .. ; done || cd .. ; ls;}
ntfy () { curl -d "$1" "ntfy.sh/$(<~/.secrets/ntfy)" >> /dev/null }
pdf() {sioyek "${1}" &disown; exit;}
yud () { yay; [[ "${?}" -eq 0 ]] && ntfy "Upgrade Complete" || ntfy "Upgrade Failed" ;}

if [[ -z ${SSH_TTY} ]] then
    source ~/.config/zsh/local
else
    source ~/.config/zsh/tty
fi

MYPS1=$'%F{white} %~ %B%F{green}%F{magenta}%F{cyan}%f%b '
MYPS2="%F{white} %~ %F{green}i %F{cyan}%B%f%b "

alias r="nvim --cmd 'let R_auto_start = 1 | let R_objbr_auto_start = 1'"
alias lf='lfub'
alias la='ls -a'
alias pgrep='pgrep -l'
alias chunkers='nvim -u NONE -c "set nowrap"'
alias du='du -h'
alias grep='grep --color'
alias ffmpeg='noglob ffmpeg -hide_banner'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias mpv='noglob mpv'
alias mv='mv -i'
alias ttop='top | head'
alias view='nvim -R'
alias vimdiff='nvim -d'
alias vi=nvim
alias wiki='nvim -c VimwikiIndex'
#alias xev='alacritty -e xev'
alias yt-dlp='noglob yt-dlp'


setopt incappendhistory
setopt appendhistory
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -v
export KEYTIMEOUT=1

#tab completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Edit line in vim with ctrl-v:
autoload edit-command-line; zle -N edit-command-line
bindkey '^V' edit-command-line

# Backward search with ctl-r
# autoload -Uz history-search-end
# zle -N history-beginning-search-backward-end history-search-end
# zle -N history-beginning-search-forward-end history-search-end
# bindkey '^R' history-incremental-search-backward

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Change prompt when vi or normal mode
function zle-line-init zle-keymap-select {
    # F_PREFIX="${CONDA_PROMPT_MODIFIER}${MYPREFIX}"
    F_PREFIX="${MYPREFIX}"
    case $KEYMAP in
        viins|main)
            PS1="${F_PREFIX}${MYPS1}";;
        vicmd)
            PS1="${F_PREFIX}${MYPS2}";;
    esac
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# Fix normal mode after vi
zle -A kill-whole-line vi-kill-line
zle -A backward-kill-word vi-backward-kill-word
zle -A backward-delete-char vi-backward-delete-char

# File manager function
lcd() {
    lf -last-dir-path /tmp/lastdir
    dir=$(cat /tmp/lastdir)
    cd "$dir"
}

# Customize some keys
bindkey     "^[[H"      beginning-of-line
bindkey     "^[[F"      end-of-line
bindkey     "^[[3~"     delete-char
bindkey     "^[[5~"     beginning-of-history
bindkey     "^[[6~"     end-of-history
bindkey     '^w'        backward-kill-word
bindkey     "^A"        beginning-of-line
bindkey     "^E"        end-of-line
bindkey     "^U"        backward-kill-line
bindkey     "^?"        backward-delete-char
bindkey     "^o"        kill-whole-line
bindkey     "^ "        autosuggest-accept
bindkey -a  "^[[3~"     delete-char
bindkey -a  "^?"        backward-delete-char
bindkey -a  "^["        vi-insert
bindkey -s  "^h"        "^[k0"
bindkey -s  "^d"        "^olcd\n"
#bindkey -s  "^d"        "^[dT/xa"

# Use vim keys in tab complete menu:
bindkey -M  menuselect  'h'     vi-backward-char
bindkey -M  menuselect  'k'     vi-up-line-or-history
bindkey -M  menuselect  'l'     vi-forward-char
bindkey -M  menuselect  'j'     vi-down-line-or-history
bindkey -M  menuselect  '^['    send-break

# Plugins
source ~/.config/zsh/plugins/pass.zsh-completion 2>/dev/null
source ~/.config/zsh/plugins/syntax_highlighting/zsh-syntax-highlighting.plugin.zsh 2> /dev/null
source ~/.config/zsh/plugins/history_substring/zsh-history-substring-search.plugin.zsh 2> /dev/null
source ~/.config/zsh/plugins/autosuggestions/zsh-autosuggestions.plugin.zsh 2> /dev/null

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
    # eval "$__conda_setup"
# else
    # if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        # . "/opt/miniconda3/etc/profile.d/conda.sh"
    # else
        # export PATH="/opt/miniconda3/bin:$PATH"
    # fi
# fi
# unset __conda_setup
# <<< conda initialize <<<
